<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Disclaimer dashboard Language Lines
    |--------------------------------------------------------------------------
    */

    "disclaimer"        => "Disclaimer",
    "disclaimer_header" => "General Disclaimer and Conditions",
    "disclaimer_text"   => "<p>The information appearing on this website, including discussion papers, videos or other graphics (the “Information Material”) has been prepared for and is issued by TOR-X Network Ltd for informational purposes only and may be amended, superseded or replaced.  The Information Material is subject to update and does not constitute a prospectus or offer document, invitation or offer to buy any instrument of any sort.</p><p>If any of the Information Material is updated with a new version after you accessed or received an older version, you are solely responsible for accessing or receiving the most up-to-date version.  We disclaim any liability in connection with any Information Material that has been superseded by newer versions.</p><p>The Information Material relates primarily to the intended development and use of the TOR-X.network blockchain-based ecosystem by various participants and members.  Some of the Information Material relates to the proposed sale to certain eligible potential purchasers by TOR-X Network Ltd of cryptographic tokens to be used in the TOR-X Network ecosystem (“TOR-X Tokens”).  No regulatory authority in Singapore, including the Monetary Authority of Singapore, has reviewed or approved the TOR-X Tokens or any of the Information Material.  The purchase of tokens through the Whitelisting Process is subject to a potential purchaser’s compliance with the Whitelisting Terms and Conditions.</p><p>The Information Material does not constitute either an offer or solicitation of securities or any other regulated product and is neither a promotion, invitation nor solicitation for investment purposes.  The TOR-X Tokens do not represent equity, shares, units, royalties or rights to capital, profit, returns or income in the TOR-X Network ecosystem or technologies in TOR-X Network Limited, TOR-X Network Ltd or any other company or intellectual property associated with the TOR-X Network ecosystem, or any other public or private enterprise, corporation, foundation or other entity in any jurisdiction.  The TOR-X Tokens are not intended to represent a security or similar legal interest.</p><p>
No information or opinion presented herein is intended as specific recommendations or to form the basis for any purchase or investment decision.  Accordingly, the Information Material does not constitute investment advice or counsel or a solicitation for investment in any token or instrument.  Prospective purchasers should consult with their professional advisors and advisors as needed prior to coming to their own conclusion on whether to purchase the TOR-X Tokens.</p><p>The purchase of TOR-X Tokens carries with it significant risks and is inherently speculative in nature.  Prospective purchasers should carefully assess and take into account such risks prior to purchasing TOR-X Tokens.  TOR-X Network Limited and its affiliates, including TOR-X Network Ltd and all of their collective past, present or future officers, directors, managers, employees, agents, advisors or consultants, or any other person (collectively, “TOR-X”), expressly disclaims any and all responsibility for any direct or consequential loss or damage of any kind whatsoever arising directly or indirectly from: (a) reliance on any information contained in the Information Material; (b) any error, omission or inaccuracy in any such information; and (c) any action resulting therefrom.  TOR-X does not guarantee the accuracy of the statements made or conclusions reached in the Information Material and does not make, and expressly disclaims, all representations and warranties (whether express or implied by statute or otherwise). The Information Material does not constitute advice, nor any recommendations, by TOR-X or any of its affiliates and all of their collective past, present or future officers, directors, managers, employees, agents, advisors or consultants, or any other person, to any recipient of the Information Material.</p><p>No regulatory authority has examined or approved any information set forth in the Information Material.  No such action has been or will be taken under the laws, regulatory requirements or rules of any jurisdiction.  The publication, distribution or dissemination of the Information Material does not imply that applicable laws, regulatory requirements or rules have been complied with.</p><p>The distribution or dissemination of the Information Material or any part thereof may be prohibited or restricted by the laws, regulatory requirements and rules of any jurisdiction.  Persons to whom a copy of the Information Material has been distributed or disseminated or provided access to, or who otherwise have the Information Material in their possession, shall not circulate to any other persons, reproduce or otherwise distribute the Information Material or any information contained herein for any purpose whatsoever nor permit or cause the same to occur.</p><p>
References in the Information Material to specific companies are for reference purposes only.  The use of any company(ies) or product name(s) and/or trademark(s) does not imply any affiliation with, or endorsement by, any of those parties.</p>
<p>CAUTION REGARDING FORWARD-LOOKING STATEMENTS</p>
<p>Certain statements in the Information Material may constitute “forward-looking information” under various securities laws.  In some cases, these forward-looking statements can be identified by words or phrases such as “may,” “will,” “expect,” “anticipate,” “aim,” “estimate,” “intend,” “plan,” “seek,” “believe,” “potential,” “continue,” “is/are likely to” or the negative of such terms, or other similar expressions intended to identify forward-looking statements.  Forward looking statements are provided to allow prospective purchasers of the TOR-X Tokens the opportunity to understand TOR-X’s beliefs and opinions in respect of the potential future, including forward-looking statements related to the proposed operating model for TOR-X’s, which should not be construed as a forecast, projection or prediction of future results of TOR-X’s operations.</p>
<p>The forward-looking statements are not guarantees of future performance, and undue reliance should not be placed on them.  Forward-looking statements are based on certain assumptions and analysis based on current estimates, assumptions, conditions and expected future developments and other factors TOR-X believes are appropriate.</p>
<p>These forward-looking statements involve known and unknown risks, uncertainties and other factors that may cause the actual future success of TOR-X, the TOR-X Tokens or TOR-X or its performance to be materially different from any future results, performance or achievements expected, expressed or implied by such forward-looking statements.  These factors include, but are not limited to, risks associated with:</p>
    <p>
        <ul> 
        <li>   TOR-X’s ability to launch and develop the TOR-X.network platform or ecosystem;</li> 
        <li>    TOR-X’s businesses and operations;</li> 
        <li>    TOR-X Token’s reliance on Ethereum or other blockchains;</li> 
        <li>    unfavorable legal or regulatory actions;</li> 
        <li>    tax treatment of TOR-X Tokens;</li> 
        <li>    a restriction of transfer of TOR-X Tokens;</li> 
        <li>    a user’s inability to access their TOR-X.network wallets;</li> 
        <li>    the compromise of a user’s credentials;</li> 
        <li>    insufficient interest in the TOR-X platform, ecosystem or blockchain technologies;</li> 
        <li>    TOR-X’s ability to continuously adapt its business model to meet market needs;</li> 
        <li>    competitive technologies;</li> 
        <li>    security weaknesses;</li> 
        <li>    TOR-X’s ability to effectively protect its intellectual property;</li> 
        <li>    meeting regulatory obligations in the countries in which TOR-X intends to operate; and</li> 
        <li>    meeting users’ expectations regarding the functionality of the TOR-X ecosystem.</li> 
        </ul>
    </p> 
<p>NO PUBLIC OFFER IN THE UNITED STATES</p> 
<p>The TOR-X Tokens will not be publicly offered or sold in the United States.  If you access or receive Information Material as a U.S. person or from within the United States as part of a private sale, you are hereby deemed to have represented that you are an “accredited investor” as defined in Rule 501 of Regulation D of the U.S. Securities Act of 1933.  A U.S. person is a citizen or permanent resident of the United States or an individual or entity with primary residence or domicile in the United States.</p> 
 
<p>RESTRICTIONS ON DISTRIBUTION</p> 
<p>The distribution or dissemination of the Information Material or any part thereof may be prohibited or restricted by the laws, regulatory requirements and rules of any jurisdiction.  In the case where any restriction applies, you must inform yourself about, and observe, any restrictions that are applicable to your possession of the Information Material or any part thereof at your own expense and without liability to TOR-X.  The Information Material may not be redistributed, reproduced, published or passed on to any other person, in part or in whole, for any purpose, without the express prior written consent of TOR-X.</p> 
 
<p>LAST UPDATED 1 December 2018 </p> ",

];