<?php

/**
 * FAQ section
 */

return [

    //text
    "section_caption"   => "Have Any Questions?",
    "section_text_1"    => "Frequently asked questions (FAQ) or Questions and Answers (Q&A), are listed questions and answers, all supposed to be commonly asked in some context",


    // General
    "general_caption"   => "General",

    "gen_question_1"    => "What is cryptocurrency?",
    "gen_answer_1"      => "The best cryptocurrency to buy is one we are willing to hold onto even if it goes down. 
    For example, I believe in Steem enough that I am willing to hold it even if it goes down 99% and would start 
    buying more of it if the price dropped.",

    "gen_question_2"    => "Which cryptocurrency is best to buy today?",
    "gen_answer_2"      => "The best cryptocurrency to buy is one we are willing to hold onto even if it goes down. 
    For example, I believe in Steem enough that I am willing to hold it even if it goes down 99% and would start 
    buying more of it if the price dropped.",

    "gen_question_3"    => "How about day trading crypto?",
    "gen_answer_3"      => "While profits are possible trading cryptocurrencies, so are losses. 
    My first year involved me spending hundreds of hours trading Bitcoin with a result of losing over $5,000 with nothing 
    to show for it. Simply trading digital currencies is very similar to gambling because no one really knows what is 
    going to happen next although anyone can guess! While I was lucky to do nothing expect lose money when I started, 
    the worst thing that can happen is to get lucky right away and get a big ego about what an amazing cryptocurrency trader we are.",

    "gen_question_4"    => "When to sell a cryptocurrency?",
    "gen_answer_4"      => "Before Steem I was all in an another altcoin and really excited about it. 
    When I first bought the price was low and made payments to me every week just for holding it. 
    As I tried to participate in the community over the next several months, I was consistently met with a mix of 
    excitement and hostility. When I began talking openly about this, the negative emotions won over in the community and in me. 
    Originally I had invested and been happy to hold no matter what the price which quickly went up after I bought it. ",


    // Pre ICO
    "pre_ico_caption"   => "Node Pre-Sale",

    "pre_question_1"    => "Why node Pre-Sale?",
    "pre_answer_1"      => "Node Pre-Sale stage was made to let ",

    "pre_question_2"    => "Can I make money with Bitcoin?",
    "pre_answer_2"      => "You should never expect to get rich with Bitcoin or any emerging technology. 
    It is always important to be wary of anything that sounds too good to be true or disobeys basic economic rules.",

    "pre_question_3"    => "What happens when bitcoins are lost?",
    "pre_answer_3"      => "When a user loses his wallet, it has the effect of removing money out of circulation. 
    Lost bitcoins still remain in the block chain just like any other bitcoins. However, lost bitcoins remain dormant 
    forever because there is no way for anybody to find the private key(s) that would allow them to be spent again. 
    Because of the law of supply and demand, when fewer bitcoins are available, the ones that are left will be in higher 
    demand and increase in value to compensate.",

    "pre_question_4"    => "Who controls the Bitcoin network?",
    "pre_answer_4"      => "Nobody owns the Bitcoin network much like no one owns the technology behind email. 
    Bitcoin is controlled by all Bitcoin users around the world. While developers are improving the software, 
    they can't force a change in the Bitcoin protocol because all users are free to choose what software and version 
    they use.",


    // ICO Tokens
    "ico_caption"       => "ICO Tokens",

    "ico_question_1"    => "How are bitcoins created?",
    "ico_answer_1"      => "New bitcoins are generated by a competitive and decentralized process called 'mining'. 
    This process involves that individuals are rewarded by the network for their services. 
    Bitcoin miners are processing transactions and securing the network using specialized hardware and are collecting new 
    bitcoins in exchange.",

    "ico_question_2"    => "Why do bitcoins have value?",
    "ico_answer_2"      => "Bitcoins have value because they are useful as a form of money. Bitcoin has the characteristics 
    of money (durability, portability, fungibility, scarcity, divisibility, and recognizability) based on the properties 
    of mathematics rather than relying on physical properties (like gold and silver) or trust in central authorities 
    (like fiat currencies). In short, Bitcoin is backed by mathematics.",

    "ico_question_3"    => "What determines bitcoin's price?",
    "ico_answer_3"      => "The price of a bitcoin is determined by supply and demand. When demand for bitcoins increases, 
    the price increases, and when demand falls, the price falls. There is only a limited number of bitcoins in circulation 
    and new bitcoins are created at a predictable and decreasing rate",

    "ico_question_4"    => "Can bitcoins become worthless?",
    "ico_answer_4"      => "Yes. History is littered with currencies that failed and are no longer used, such as the 
    German Mark during the Weimar Republic and, more recently, the Zimbabwean dollar.",


    // Client
    "cli_caption"       => "Client",

    "cli_question_1"    => "How does one acquire bitcoins?",
    "cli_answer_1"      => "While it may be possible to find individuals who wish to sell bitcoins in exchange for a credit 
    card or PayPal payment, most exchanges do not allow funding via these payment methods. 
    This is due to cases where someone buys bitcoins with PayPal, and then reverses their half of the transaction. 
    This is commonly referred to as a chargeback.",

    "cli_question_2"    => "Can I make money with Bitcoin?",
    "cli_answer_2"      => "You should never expect to get rich with Bitcoin or any emerging technology. 
    It is always important to be wary of anything that sounds too good to be true or disobeys basic economic rules.",

    "cli_question_3"    => "What happens when bitcoins are lost?",
    "cli_answer_3"      => "When a user loses his wallet, it has the effect of removing money out of circulation. 
    Lost bitcoins still remain in the block chain just like any other bitcoins. However, lost bitcoins remain dormant 
    forever because there is no way for anybody to find the private key(s) that would allow them to be spent again. 
    Because of the law of supply and demand, when fewer bitcoins are available, the ones that are left will be in higher 
    demand and increase in value to compensate.",

    "cli_question_4"    => "Who controls the Bitcoin network?",
    "cli_answer_4"      => "Nobody owns the Bitcoin network much like no one owns the technology behind email. 
    Bitcoin is controlled by all Bitcoin users around the world. While developers are improving the software, 
    they can't force a change in the Bitcoin protocol because all users are free to choose what software and version they use.",


    // Legal
    "legal_caption"       => "Legal",

    "leg_question_1"    => "Is Bitcoin legal?",
    "leg_answer_1"      => "To the best of our knowledge, Bitcoin has not been made illegal by legislation in most jurisdictions. 
    However, some jurisdictions (such as Argentina and Russia) severely restrict or ban foreign currencies. 
    Other jurisdictions (such as Thailand) may limit the licensing of certain entities such as Bitcoin exchanges.",

    "leg_question_2"    => "Is Bitcoin useful for illegal activities?",
    "leg_answer_2"      => "Bitcoin is money, and money has always been used both for legal and illegal purposes. 
    Cash, credit cards and current banking systems widely surpass Bitcoin in terms of their use to finance crime. 
    Bitcoin can bring significant innovation in payment systems and the benefits of such innovation are often considered 
    to be far beyond their potential drawbacks.",

    "leg_question_3"    => "Can Bitcoin be regulated?",
    "leg_answer_3"      => "The Bitcoin protocol itself cannot be modified without the cooperation of nearly all its users, 
    who choose what software they use. Attempting to assign special rights to a local authority in the rules of the global 
    Bitcoin network is not a practical possibility.",

    "leg_question_4"    => "What about Bitcoin and taxes?",
    "leg_answer_4"      => "Bitcoin is not a fiat currency with legal tender status in any jurisdiction, but often tax 
    liability accrues regardless of the medium used. There is a wide variety of legislation in many different jurisdictions 
    which could cause income, sales, payroll, capital gains, or some other form of tax liability to arise with Bitcoin.",
];
